### ISSUE TITLE
assert_multi_tx1.sol

### ISSUE THREAD

**Issue by feliam** [EthereumAnalysisBenchmarks/ethereum-analyzer-suites-runner#31]
True positive, False negative, truly positiveness?

What's the tx trace to set the storage variable "param" to 0(zero) ?

pragma solidity ^0.4.19;

contract Benchmark {
    uint256 private param;

    function Benchmark(uint256 _param) public {
        require(_param > 0);
        param = _param;
    }

    function run() {
        assert(param > 0);
    }

}

**Comment by rocky** [comment]
@feliam @suhabe Ok. I must have made a mistake in the configuration. I will fix that soon, but report update may take a little while as there are a number of moving parts. 

If you find other problems like the please let me know. 

(I make a lot of mistakes - that's why  I've written so many debuggers)

**Comment by rocky** [comment]
Fixed on master now.
